hr_gpb/api/urls.py
from django.urls import include, path
from . import views

app_name = 'api'

urlpatterns = [
    path('vacancy_list/', views.vacancy_list, name='vacancy_list'),
    path('vacancy_list/<str:vacancy_id>', views.vacancy_page, name='vacancy_page')
    
]

hr_gpb/crm/urls.py
from django.urls import include, path
# from rest_framework import routers
from . import views

# router = routers.DefaultRouter()
# router.register(r'ym_tokens', views.YandexOAuthViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
app_name = 'crm'

urlpatterns = [
      path('',  views.index, name='crm_index'),
      path('vacancies/',  views.vacancies_list, name='vacancies_list'),
      path('add_vacancy/',  views.add_vacancy, name='add_vacancy'),
      path('vacancies/detail/<int:vacancy_id>', views.vacancies_detail, name='vacancy_details'),

      path('candidates/',  views.candidates_list, name='candidates_list'),
      path('candidates/detail/<int:candidat_id>', views.candidates_detail, name='candidat_details'),

      path('ca/<int:ca_id>', views.ca_details, name='ca_details'),


]

hr_gpb/hr_gpb/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url

from django.conf import settings
from django.conf.urls.static import static

from crm import views

urlpatterns = [
    path('',  views.index, name='crm_index'),

    path('admin/', admin.site.urls),
    path('crm/', include('crm.urls')),
    path('tests/', include('tests.urls')),
    path('api/', include('api.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hr_gpb/crm/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings
from model_utils import Choices

from tests.models import Testing, TestingSolution 


def default_time():
    return timezone.now()

class Candidate(models.Model):
      fullname = models.CharField(max_length=200, null=True, blank=True)
      phone = models.CharField(max_length=24, null=True, blank=True)
      email = models.EmailField(max_length=254, null=True, blank=True)
      
      created = models.DateTimeField(default=default_time)
      updated = models.DateTimeField(auto_now=True)

      def __str__(self):
            return self.fullname

class Skill(models.Model):
      TYPES = Choices(
            (1, "hard", "Hard skill"),
            (2, "soft", "Soft skill"),
        )
      title = models.CharField(max_length=200, null=True,
        blank=True, default="Навык")
      type = models.IntegerField(choices=TYPES, default=TYPES.hard, null=True)

      created = models.DateTimeField(default=default_time)

      def __str__(self):
        return f"{self.title}"

class Duty(models.Model):
    title = models.CharField(max_length=200, null=True,
        blank=True, default="Обязанность")
    created = models.DateTimeField(default=default_time)

    def __str__(self):
        return f"{self.title}"

class Сondition(models.Model):
    title = models.CharField(max_length=200, null=True,
        blank=True, default="Условие")

    created = models.DateTimeField(default=default_time)

    def __str__(self):
        return f"{self.title}"


class Vacancy(models.Model):
    STATUSES = Choices(
        (0, "new", "Новая"),
        (1, "execution", "В работе"),
        (100, "success", "Закрыта"),
    )
    CITIES = Choices(
        (0, "any", "Любой"),
        (1, "moscow", "Москва"),
        (2, "kaliningrad", "Калининград"),
        (3, "kazan", "Казань"),
        (4, "spb", "Санкт-Петербург"),
        (5, "krasnodar", "Краснодар"),
    )
    title = models.CharField(max_length=200, null=True,
                            blank=True, default="Вакансия #")
    owner = models.ForeignKey(settings.AUTH_USER_MODEL,
                              on_delete=models.CASCADE)
    
    recruter = models.ForeignKey(settings.AUTH_USER_MODEL,
                              on_delete=models.CASCADE, related_name="vacancy_recruter", null=True, blank=True)
    status = models.IntegerField(choices=STATUSES, default=STATUSES.new, null=True)
    description = models.TextField(null=True, blank=True)
    duties = models.ManyToManyField(
        Duty, blank=True, related_name="vacancy_duties"
    )
    experience = models.IntegerField(null=True)
    
    key_skills = models.ManyToManyField(
        Skill, blank=True, related_name="vacancy_key_skills"
    )
    additional_skills = models.ManyToManyField(
        Skill, blank=True, related_name="vacancy_additional_skills"
    )
    conditions = models.ManyToManyField(
        Сondition, blank=True, related_name="vacancy_conditions"
    )
    city = models.IntegerField(choices=CITIES, default=CITIES.any, null=True)

    testing = models.ForeignKey(Testing, blank=True, null=True, default=None, related_name="vacancy_test", on_delete=models.CASCADE)

    code_reviewer = models.ForeignKey(settings.AUTH_USER_MODEL,
                              on_delete=models.CASCADE, related_name="vacancy_code_reviewer", null=True, blank=True)

    created = models.DateTimeField(default=default_time)
    updated = models.DateTimeField(auto_now=True)
    deadline = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.title


class CandidateApplication(models.Model):
    SOURCES = Choices(
        (0, "website", "Сайт"),
        (1, "hh", "HeadHunter"),
        (2, "sj", "SuperJob"),
    )
    STATUS = Choices(
        (0, "decline", "Отказ"),
        (1, "new", "Новая"),
        (2, "interview", "Собеседование"),
        (3, "secure", "Служба безопасности"),
        (4, "offer", "Оффер"),
    )

    core_condidate = models.ForeignKey(
    Candidate, blank=True, related_name="condidate_applicatin", on_delete=models.CASCADE)
    core_vacancy = models.ForeignKey(
    Vacancy, blank=True, related_name="vacancy_applicatin", on_delete=models.CASCADE)

    testing_solution = models.ForeignKey(TestingSolution, blank=True, null=True, default=None, related_name="vacancy_test", on_delete=models.CASCADE)

    status = models.IntegerField(choices=STATUS, default=STATUS.new)
    source = models.IntegerField(choices=SOURCES, default=SOURCES.website)
    cv_file = models.FileField(null=True, blank=True)
    cv_recognition = models.TextField(null=True, blank=True)
    skills_assessment = models.JSONField(default={})
    key_skills_conformity = models.IntegerField(default=0)
    additional_skills_conformity = models.IntegerField(default=0)

    created = models.DateTimeField(default=default_time)

    def __str__(self):
        return f"{self.core_condidate} -> {self.core_vacancy} от {self.created}"

hr_gpb/crm/forms.py
from django import forms

from .models import Candidate, Vacancy, CandidateApplication


# Прием резюме с сайта
class CandidateApplicationForm(forms.ModelForm):

      candidate_name = forms.CharField(label='Ваше имя')
      phone = forms.CharField(label='Телефон')
      email = forms.EmailField(label='Электронная почта')
      candidate_id = forms.CharField(widget=forms.HiddenInput(), required=False)

      class Meta:
            model = CandidateApplication
            fields = ('cv_file', )

            labels = {
                  'cv_file': "Резюме",
            }


      def __init__(self, vacancy_id, *args, **kwargs):
            super(CandidateApplicationForm, self).__init__(*args, **kwargs)

      def save(self, commit=True):
            
        candidate, created = Candidate.objects.get_or_create(
          email = self.cleaned_data['email'],
          )
        
        if created:
              candidate.fullname = self.cleaned_data['candidate_name']
              print(candidate.fullname)
              candidate.email = self.cleaned_data['email']
              candidate.phone = self.cleaned_data['phone']
              candidate.save()

        return super(CandidateApplicationForm, self).save(commit)


class AddVacancyForm(forms.ModelForm):
      class Meta:
            model = Vacancy
            fields = ('title', 'owner', 'recruter', 'status', 'description', 'duties', 'experience', 'key_skills', 'additional_skills', 'conditions', 'city', 'testing', 'code_reviewer' )

            labels = {
                  'title': 'Заголовок',
                  'owner': 'Заказчик',
                  'recruter': 'Рекрутер',
                  'status': 'Статус',
                  'description': 'Описание',
                  'duties': 'Обязанности',
                  'experience': 'Опыт',
                  'key_skills': 'Ключевые навыки',
                  'additional_skills': 'Вспомогательные навыки',
                  'conditions': 'Условия работы',
                  'city': 'Город',
                  'testing': 'Тестовое задание',
                  'code_reviewer': 'Ответственный за код-ревью'
            }

hr_gpb/crm/views.py
from django.shortcuts import render, get_object_or_404
from django.views.decorators.csrf import csrf_exempt
from django.db.models import Count
import sys, os, json

from .models import Vacancy, Skill, Candidate, CandidateApplication
from .forms import AddVacancyForm

from api.views import send_notification

# ДЕМО
from pdfminer.high_level import extract_text

from natasha import (
    Segmenter,
    
    NewsEmbedding,
    NewsMorphTagger,
    NewsSyntaxParser,

    MorphVocab,
    
    Doc, 

    NamesExtractor,
    PER
)



def index(request):

    data = {
        "StagesApplications": [CandidateApplication.objects.filter(status=1).count(), CandidateApplication.objects.filter(status=2).count(), CandidateApplication.objects.filter(status=3).count(), CandidateApplication.objects.filter(status=4).count(),]
    }
    
    return render(request, 'index.html', context={"data": data})

def vacancies_list(request):

    all_vacancys = Vacancy.objects.all()

    application_stat = []
    print(all_vacancys)
    for vacancy in all_vacancys:
        ca = CandidateApplication.objects.filter(core_vacancy=vacancy).values('status').annotate(dcount=Count('status'))

        application_stat.append(list(ca.values_list('dcount', flat=True)))

    print(application_stat)

    # При отсутствующей авторизации
    # try:
    #     my_vacancys = Vacancy.objects.filter(owner = request.user)
    # except:
    #     my_vacancys = Vacancy.objects.all()

    vacancy_data = zip(all_vacancys, application_stat)
    data = {
        "all_vacancys": all_vacancys,
        "application_stat": application_stat,
        "vacancy_data": vacancy_data
        # 'my_vacancys': my_vacancys
    }

    return render(request, 'vacancy.html', context={'data': data})

def add_vacancy(request):

    if request.method == "POST":

            vacancy_form = AddVacancyForm(request.POST)

            if vacancy_form.is_valid():
                print('Форма ВАЛИДНА')
                add_vacancy = vacancy_form.save(commit=False)

                send_notification(f'{add_vacancy.owner}, вакансия по вашему запросу создана \nРекрутер вакансии: {add_vacancy.recruter}\nКод-ревью проводит {add_vacancy.code_reviewer}')
                add_vacancy.save()

    data = {
        "form": AddVacancyForm()
    }
   
    return render(request, 'add_vacancy.html', context={'data': data})

@csrf_exempt
def vacancies_detail(request, vacancy_id):
    vacancy = get_object_or_404(Vacancy, id=vacancy_id)
    if request.method == "POST":
        ca = CandidateApplication.objects.get(id=request.POST['application'])
        if request.POST['status'] == 'trash':
            ca.status = 0
        else:
            ca.status += 1
        
        ca.save()

    data = {
        "vacancy": vacancy,
        "vacancy_requests": {
            "new": CandidateApplication.objects.filter(core_vacancy=vacancy, status=1).order_by('-key_skills_conformity'),
            "interview": CandidateApplication.objects.filter(core_vacancy=vacancy, status=2).order_by('-key_skills_conformity'),
            "secure": CandidateApplication.objects.filter(core_vacancy=vacancy, status=3).order_by('-key_skills_conformity'),
            "offer": CandidateApplication.objects.filter(core_vacancy=vacancy, status=4).order_by('-key_skills_conformity'),
            "decline": CandidateApplication.objects.filter(core_vacancy=vacancy, status=0).order_by('-key_skills_conformity')
        },
    }
    
    return render(request, 'vacancy_detail.html', context={'data': data})

def candidates_list(request):
    all_candidates = Candidate.objects.all()

    data = {
        'all_candidates': all_candidates,
        # 'my_candidates': my_candidates
    }

    return render(request, 'candidates.html', context={'data': data})

def candidates_detail(request, candidat_id):
    return render(request, 'candidates.html', context={'data': 'data'})



# Дебаг
def ca_details(request, ca_id):

    ca = get_object_or_404(CandidateApplication, id=ca_id)

    vacancy_key_skills = list(map(lambda x:x.lower(),list(ca.core_vacancy.key_skills.all().values_list('title', flat=True))))
    vacancy_additional_skills = list(map(lambda x:x.lower(),list(ca.core_vacancy.additional_skills.all().values_list('title', flat=True))))

    segmenter = Segmenter()
    emb = NewsEmbedding()
    morph_tagger = NewsMorphTagger(emb)
    syntax_parser = NewsSyntaxParser(emb)
    morph_vocab = MorphVocab()

    text = extract_text(ca.cv_file.path)

    doc = Doc(text)

    doc.segment(segmenter)
    doc.tag_morph(morph_tagger)
    doc.parse_syntax(syntax_parser)

    cv_key_skills = []
    cv_additional_skills = []

    for token in doc.tokens:
        token.lemmatize(morph_vocab)
        print(token)
        if token.lemma in vacancy_key_skills and token.lemma not in cv_key_skills:
            cv_key_skills.append(token.lemma)
            print(token.lemma)

        if token.lemma in vacancy_additional_skills and token.lemma not in cv_additional_skills:
            cv_additional_skills.append(token.lemma)
            print(token.lemma)
    

    candidate_conformity = {
        "key_skills": {
            "vacancy_key_skills": vacancy_key_skills,
            "cv_key_skills": cv_key_skills,
            "conformity_percent": len(cv_key_skills) / len(vacancy_key_skills)
        },
        "additional_skills": {
            "vacancy_additional_skills": vacancy_additional_skills,
            "cv_additional_skills": cv_additional_skills,
            "conformity_percent": len(cv_additional_skills) / len(vacancy_additional_skills)
        }
    }
    

    return render(request, 'demo_data.html', context={'data': json.dumps(candidate_conformity)})



def demo_task(request):
    return render(request, 'demo_task.html', context={'data': "data"})

hr_gpb/crm/templates/add_vacancy.html
{% extends "base.html" %} {% load static %}
{% load crispy_forms_tags %}
{% block main %}
<div class="row justify-content-center">
          <div class="col-12 ">

            <!-- Header -->
            <div class="header mt-md-5">
              <div class="header-body">

              <div class="row">
                <div class="col">
                  <h1 class="header-title">
                    Добавить вакансию
                  </h1>
                </div>
              </div>
            </div>
          </div>


            <!-- Card -->

            <!-- Files -->
            <div class="card" data-list='{"valueNames": ["name"]}'>
              <div class="card-header">

                <!-- Title -->
                <h4 class="card-header-title">
                  Список вакансий
                </h4>

              </div>
              <div class="card-body">

              <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                
                {{ data.form|crispy }}
                
                <button type="submit" class="btn btn-primary">Отправить</button>
              </form>

              </div>
            </div>
          </div>
        </div>



              </div>
            </div>

          </div>
        </div> <!-- / .row -->

{% endblock main %}

hr_gpb/crm/templates/candidat_list_item.html
<li class="list-group-item">
  <div class="row align-items-center">
    <div class="col-auto">

      <!-- Avatar -->
      <a href="{% url 'crm:candidat_details' candidat.id %}" class="avatar avatar-md">
        <div class="avatar avatar-md">
          <span class="avatar-title rounded-circle">CF</span>
        </div>
      </a>

    </div>
    <div class="col ml-n2">

      <!-- Title -->
      <h4 class="mb-1 name">
        <a href="{% url 'crm:candidat_details' candidat.id %}">{{ candidat.fullname }}</a>
      </h4>

      <!-- Text -->
      <p class="card-text small text-muted mb-1">
        CTO отдела разработки внутренней HR-системы
      </p>

      <!-- Time -->
      <p class="card-text small text-muted">
        {{ candidat.city }}
      </p>

    </div>
  </div> <!-- / .row -->
</li>

hr_gpb/crm/templates/candidates.html
{% extends "base.html" %} {% load static %}
{% block main %}
<div class="row justify-content-center">
          <div class="col-12 ">

            <!-- Header -->
            <div class="header mt-md-5">
              <div class="header-body">

                <!-- Title -->
                <h1 class="header-title">
                  Кандидаты
                </h1>

              </div>
            </div>


            <!-- Card -->

            <!-- Files -->
            <div class="card" data-list='{"valueNames": ["name"]}'>
              <div class="card-header">

                <!-- Title -->
                <h4 class="card-header-title">
                  Список кандидатов
                </h4>

              </div>
              <div class="card-header">

                <!-- Form -->
                <form>
                  <div class="input-group input-group-flush input-group-merge">

                    <!-- Input -->
                    <input type="search" class="form-control form-control-prepended search" placeholder="Поиск">

                    <!-- Prepend -->
                    <div class="input-group-prepend">
                      <div class="input-group-text">
                        <span class="fe fe-search"></span>
                      </div>
                    </div>

                  </div>
                </form>

              </div>
              <div class="card-body">

                <!-- List -->
                <ul class="list-group list-group-lg list-group-flush list my-n4">



                  {% for candidat in data.all_candidates %}
                        {% include 'candidat_list_item.html' with candidat=candidat %}
                  {% endfor %}


                </ul>
              </div>
            </div>
          </div>
        </div>



              </div>
            </div>

          </div>
        </div> <!-- / .row -->

{% endblock main %}

hr_gpb/crm/templates/demo_data.html
{{ data }}

hr_gpb/crm/templates/demo_task.html
<iframe height="900px" width="100%" src="https://repl.it/@vmoshikov/MintcreamAllGnudebugger?lite=true" scrolling="no" frameborder="no" allowtransparency="true" allowfullscreen="true" sandbox="allow-forms allow-pointer-lock allow-popups allow-same-origin allow-scripts allow-modals"></iframe>

hr_gpb/crm/templates/vacancy_detail.html
{% extends "base.html" %} {% load static %}
{% block main %}

            <!-- Header -->
            <div class="header mb-md-4">
              <div class="header-body">

                <!-- Title -->
                <h1 class="header-title">
                  {{ data.vacancy.title }} <span class="badge badge-soft-{% if data.vacancy.status == 0 %}success{% elif data.vacancy.status == 1 %}primary{% else %}dark{% endif %}">{{ data.vacancy.get_status_display }}</span>
                </h1>

              </div>
            </div>


<ul class="nav nav-tabs" id="myTab" role="tablist">
      <li class="nav-item">
            <a class="nav-link active" id="general-tab" data-toggle="tab" href="#general" role="tab" aria-controls="general" aria-selected="true">О вакансии</a>
      </li>
      <li class="nav-item pl-4">
            <span class="nav-link disabled"><b>Подбор кандидатов:</b></span>
      </li>
      <li class="nav-item">
            <a class="nav-link" id="new-tab" data-toggle="tab" href="#new" role="tab" aria-controls="new" aria-selected="false">Новые <span class="badge badge-soft-dark">{{data.vacancy_requests.new.count }}</span></a>
      </li>
      {% comment %} <li class="nav-item">
            <a class="nav-link" id="tests-tab" data-toggle="tab" href="#tests" role="tab" aria-controls="tests" aria-selected="false">Тестирование <span class="badge badge-soft-dark">{{data.vacancy_requests.tests.count }}</span></a>
      </li> {% endcomment %}
      <li class="nav-item">
            <a class="nav-link" id="interview-tab" data-toggle="tab" href="#interview" role="tab" aria-controls="interview" aria-selected="false">Собеседование <span class="badge badge-soft-dark">{{data.vacancy_requests.interview.count }}</span></a>
      </li>
      <li class="nav-item">
            <a class="nav-link" id="secure-tab" data-toggle="tab" href="#secure" role="tab" aria-controls="secure" aria-selected="false">СБ <span class="badge badge-soft-dark">{{data.vacancy_requests.secure.count }}</span></a>
      </li>
      <li class="nav-item">
            <a class="nav-link" id="offer-tab" data-toggle="tab" href="#offer" role="tab" aria-controls="offer" aria-selected="false">Оффер <span class="badge badge-soft-dark">{{data.vacancy_requests.offer.count }}</span></a>
      </li>
      <li class="nav-item ml-auto">
            <a class="nav-link" id="decline-tab" data-toggle="tab" href="#decline" role="tab" aria-controls="decline" aria-selected="false">Отказ <span class="badge badge-soft-dark">{{data.vacancy_requests.decline.count }}</span></a>
      </li>
</ul>
<div class="tab-content" id="myTabContent">
      <div class="tab-pane fade show active" id="general" role="tabpanel" aria-labelledby="general-tab">

            {% include 'vacancy_detail_general_tab.html' with data=data %}

      </div>

      <div class="tab-pane fade" id="new" role="tabpanel" aria-labelledby="new-tab">

            {% include 'vacancy_detail_tabgroups.html' with applications=data.vacancy_requests.new %}

      </div>
      {% comment %} <div class="tab-pane fade" id="tests" role="tabpanel" aria-labelledby="tests-tab">
      
            {% include 'vacancy_detail_tabgroups.html' with applications=data.vacancy_requests.tests %}
      
      </div> {% endcomment %}
      <div class="tab-pane fade" id="interview" role="tabpanel" aria-labelledby="interview-tab">
      
            {% include 'vacancy_detail_tabgroups.html' with applications=data.vacancy_requests.interview %}

      </div>
      <div class="tab-pane fade" id="secure" role="tabpanel" aria-labelledby="secure-tab">
      
            {% include 'vacancy_detail_tabgroups.html' with applications=data.vacancy_requests.secure %}
      
      </div>
      <div class="tab-pane fade" id="offer" role="tabpanel" aria-labelledby="offer-tab">
      
            {% include 'vacancy_detail_tabgroups.html' with applications=data.vacancy_requests.offer %}
      
      </div>
      <div class="tab-pane fade" id="decline" role="tabpanel" aria-labelledby="decline-tab">
      
            {% include 'vacancy_detail_tabgroups.html' with applications=data.vacancy_requests.decline %}
      
      </div>
</div>

{% for requests in data.vacancy_requests %}

      {{requests.cv_file.url}}

{% endfor %}


{% endblock main %}

hr_gpb/crm/templates/vacancy_detail_general_tab.html
<div class="row">
      <div class="col-md-6 h-100 d-inline-block py-4">

       <div class="card text-left">
         <div class="card-body">
                        {{data.vacancy.description}}
            <h2><b>Предстоит заниматься:</b></h2>
            <ul>
            {% for duty in data.vacancy.duties.all %}
                  <li>{{duty}}</li>
            {% endfor %}
            </ul>

            <h2><b>От вас ожидаем:</b></h2>
            <ul>
            <li>Опыт работы/разработки с 
                  {% for key_skill in data.vacancy.key_skills.all %}
                        <span>{{key_skill.title}}, </span>
                  {% endfor %}
            </li>

            <li>Стаж работы по требуемому направлению деятельности: от {{data.vacancy.experience}} лет</li>

            <li>Профессионально значимые качества: 
                  {% for additional_skill in data.vacancy.additional_skills.all %}
                        <span>{{additional_skill.title}}, </span>
                  {% endfor %}
            
            </li>
            </ul>

            <h2><b>Мы предлагаем:</b></h2>
            <ul>
            {% for condition in data.vacancy.conditions.all %}
                  <li>{{condition}}</li>
            {% endfor %}
            </ul>

            город {{data.vacancy.get_city_display}}
         </div>
       </div>
            
      </div>
      <div class="col-md-6 h-100 d-inline-block">
            <div class="card-body">
                  
                  <div class="mb-4">
                        <span class="badge badge-soft-primary">Опубликовано на HH</span>
                        <span class="badge badge-soft-primary">Опубликовано на SuperJob</span>
                  </div>

                    <!-- List group -->
                    <div class="list-group list-group-flush list-group-activity my-n3">
                                          <div class="list-group-item">
                        <div class="row">
                          <div class="col-auto">

                            <!-- Avatar -->
                            <div class="avatar avatar-sm">
                              <div class="avatar-title font-size-lg bg-primary-soft rounded-circle text-primary">
                                <i class="fe fe-star"></i>
                              </div>
                            </div>

                          </div>
                          <div class="col ml-n2">
                            <!-- Text -->
                            <p class="small text-gray-700 mb-0">
                              Вакансия сменила статус
                            </p>

                            <!-- Time -->
                            <small class="text-muted">
                            {{data.vacancy.created}}
                            </small>

                          </div>
                        </div> <!-- / .row -->
                      </div>
                      <div class="list-group-item">
                        <div class="row">
                          <div class="col-auto">

                            <!-- Avatar -->
                            <div class="avatar avatar-sm">
                              <div class="avatar-title font-size-lg bg-primary-soft rounded-circle text-primary">
                                <i class="fe fe-mail"></i>
                              </div>
                            </div>

                          </div>
                          <div class="col ml-n2">
                            <!-- Text -->
                            <p class="small text-gray-700 mb-0">
                              Вакансия создана
                            </p>

                            <!-- Time -->
                            <small class="text-muted">
                            {{data.vacancy.created}}
                            </small>

                          </div>
                        </div> <!-- / .row -->
                      </div>
                    </div>

                  </div>
      </div>

</div>

hr_gpb/crm/templates/vacancy_detail_tabgroups.html
{% comment %} Уважаемый ревьюер, если ты смотришь на этот ~файл~ глазами, а не через скрипт, то пропусти его. Он очень плохо написан. Мне стыдно, но нет времени все исправлять.... {% endcomment %}

<div class="row">
<div class="col-md-4 h-100 d-inline-block">
      
        <div class="nav flex-column nav-pills h-100" id="v-pills-tab" role="tablist" aria-orientation="vertical">

            {% for application in applications %}

              {% include 'vacancy_detail_tab.html' with application=application %}                  

            {% endfor %}

          </div>


</div>
<div class="col-md-8 h-100 d-inline-block">

<div class="tab-content" id="v-pills-tabContent">
      <div class="tab-pane fade show active h-100" id="candidate_application_{{application.core_condidate.id}}" role="tabpanel" aria-labelledby="candidate_application_{{application.core_condidate.id}}-tab">
      <h5 class="text-muted p-6"><span class="fe fe-arrow-left mr-4"></span>Выберите кандидата</h5>
      </div>

      {% for application in applications %}

        {% include 'vacancy_detail_tab-content.html' with application=application %}    

      {% endfor %}

</div>
      
</div>
</div>

hr_gpb/crm/templates/vacancy_list_item.html
<tr>
  <td>
    <h4 class="mb-1 name">
      <a href="{% url 'crm:vacancy_details' vacancy.id %}">{{ vacancy.title }}</a>
      {% if vacancy.testing %}
      <span class="badge badge-soft-info"><span class="fe fe-zap mr-1"></span> Тестовое задание</span>
      {% endif %}
    </h4>

    <p class="card-text small text-muted">
      Заказчик: {{ vacancy.owner.first_name }} {{ vacancy.owner.last_name }} | Рекрутер: {{ vacancy.recruter.first_name }} {{ vacancy.recruter.last_name }} | {% if vacancy.code_reviewer.first_name %} КодРевью: {{ vacancy.code_reviewer.last_name }} |{% endif %} {{ vacancy.created }}
    </p>

  </td>

  <td>{{vacancy.get_status_display}}</td>

  <td>
    
    <canvas class="chart-canvas" id="minichart{{vacancy.id}}" width="75" height="35" style="display: block; max-width: 75px; max-height: 35px;"></canvas>

    <script>
      $(document).ready(function () {
            new Chart('minichart{{vacancy.id}}', {
                  type: 'bar',
                  options: {
                        tooltips: {
                              enabled: false,
                              custom: function() {}
                        },
                        scales: {
                              xAxes: [{
                                    stacked: false,
                                    display: false
                                    
                              }],
                              yAxes: [{
                                    stacked: false,
                                    display: false
                              }]
                        },
                        legend: {
                              display: false
                        },
                        layout: {
                              padding: {
                                    left: 0,
                                    right: 0,
                                    top: 0,
                                    bottom: 5
                              }
                        }
                  },
                  
                  data: {
                        labels: ['Новая', 'Собеседование', 'СБ', 'Оффер'],
                        datasets: [
                              {
                                    data: {{dataset}}
                              }
                        ]
                  }
            });
      })
</script>

  </td>
</tr>