hr_gpb/api/urls.py
from django.urls import include, path
from . import views

app_name = 'api'

urlpatterns = [
    path('vacancy_list/', views.vacancy_list, name='vacancy_list'),
    path('vacancy_list/<str:vacancy_id>', views.vacancy_page, name='vacancy_page')
    
]

hr_gpb/crm/urls.py
from django.urls import include, path
# from rest_framework import routers
from . import views

# router = routers.DefaultRouter()
# router.register(r'ym_tokens', views.YandexOAuthViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
app_name = 'crm'

urlpatterns = [
      path('',  views.index, name='crm_index'),
      path('vacancies/',  views.vacancies_list, name='vacancies_list'),
      path('add_vacancy/',  views.add_vacancy, name='add_vacancy'),
      path('vacancies/detail/<int:vacancy_id>', views.vacancies_detail, name='vacancy_details'),

      path('candidates/',  views.candidates_list, name='candidates_list'),
      path('candidates/detail/<int:candidat_id>', views.candidates_detail, name='candidat_details'),

      path('ca/<int:ca_id>', views.ca_details, name='ca_details'),


]

hr_gpb/hr_gpb/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url

from django.conf import settings
from django.conf.urls.static import static

from crm import views

urlpatterns = [
    path('',  views.index, name='crm_index'),

    path('admin/', admin.site.urls),
    path('crm/', include('crm.urls')),
    path('tests/', include('tests.urls')),
    path('api/', include('api.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hr_gpb/templates/base.html
<!doctype html>
<html lang="ru">
  <head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">

    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'img/favicon/site.webmanifest' %}">
    <link rel="mask-icon" href="{% static 'img/favicon/safari-pinned-tab.svg' %}" color="#3690eb">
    <meta name="msapplication-TileColor" content="#2b5797">
    <meta name="theme-color" content="#ffffff">

    <!-- Libs CSS -->
    <link rel="stylesheet" href="{% static 'fonts/feather/feather.min.css' %}">
    <link rel="stylesheet" href="{% static 'libs/flatpickr/dist/flatpickr.min.css' %}">
    <link rel="stylesheet" href="{% static 'libs/quill/dist/quill.core.css' %}">
    <link rel="stylesheet" href="{% static 'libs/select2/dist/css/select2.min.css' %}">
    <link rel="stylesheet" href="{% static 'libs/highlight.js/styles/vs2015.css' %}">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fullcalendar/core@4.4.0/main.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fullcalendar/bootstrap@4.4.0/main.min.css">
    <link rel="stylesheet" href="https://unpkg.com/@fullcalendar/daygrid@4.4.0/main.min.css">

    <!-- Map -->
    <link href='https://api.mapbox.com/mapbox-gl-js/v0.53.0/mapbox-gl.css' rel='stylesheet' />

    <!-- Libs JS -->
    <script src="{% static 'libs/jquery/dist/jquery.min.js' %}"></script>

    
    <script src="https://cdn.jsdelivr.net/npm/@fullcalendar/core@4.4.0/main.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@fullcalendar/core@4.4.0/locales-all.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@fullcalendar/bootstrap@4.4.0/main.min.js"></script>
    <script src="https://unpkg.com/@fullcalendar/daygrid@4.4.0/main.min.js"></script>

    <!-- Theme CSS -->
      
    <link rel="stylesheet" href="{% static 'css/theme.min.css' %}" id="stylesheetLight">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" >

    <title>Газпромбанк HR-служба</title>

    
  </head>
  <body class="">

    <!-- NAVIGATION
    ================================================== -->
    
      
        <nav class="navbar navbar-vertical fixed-left navbar-expand-md navbar-light" id="sidebar">
          <div class="container-fluid">

            <!-- Toggler -->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#sidebarCollapse" aria-controls="sidebarCollapse" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>

            <!-- Brand -->
            <a class="navbar-brand" href="{% static 'dashboard:dashboard_web' %}">
              <img src="{% static 'img/logo.svg' %}" class="navbar-brand-img 
              mx-auto" alt="...">
            </a>

            <!-- User (xs) -->
            <div class="navbar-user d-md-none">

              <!-- Dropdown -->
              <div class="dropdown">
        
                <!-- Toggle -->
                <a href="#" id="sidebarIcon" class="dropdown-toggle" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <div class="avatar avatar-sm avatar-online">
                    <img src="{% static 'img/avatars/profiles/avatar-1.jpg' %}" class="avatar-img rounded-circle" alt="...">
                  </div>
                </a>

              </div>

            </div>

            <!-- Collapse -->
            <div class="collapse navbar-collapse" id="sidebarCollapse">

              <!-- Form -->
              {% comment %} <form class="mt-4 mb-3 d-md-none">
                <div class="input-group input-group-rounded input-group-merge">
                  <input type="search" class="form-control form-control-rounded form-control-prepended" placeholder="Поиск" aria-label="Поиск">
                  <div class="input-group-prepend">
                    <div class="input-group-text">
                      <span class="fe fe-search"></span>
                    </div>
                  </div>
                </div>
              </form> {% endcomment %}
      
              <!-- Navigation -->
              <ul class="navbar-nav">
                <li class="nav-item">
                  <a class="nav-link " href="{% url 'crm:crm_index' %}">
                    <i class="fe fe-bar-chart"></i> Дашборд
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link " href="{% url 'crm:vacancies_list' %}">
                    <i class="fe fe-gitlab"></i> Вакансии
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link " href="{% url 'crm:candidates_list' %}">
                    <i class="fe fe-users"></i> Кандидаты
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#dashboard_reports" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="dashboard_reports">
                    <i class="fe fe-command"></i> Отчеты
                  </a>
                  <div class="collapse " id="dashboard_reports">
                    <ul class="nav nav-sm flex-column">
                      <li class="nav-item">
                        <a href="" class="nav-link">
                          Итоги подбора
                        </a>
                      </li>
                      <li class="nav-item">
                        <a href="" class="nav-link">
                          Активные вакансии
                        </a>
                      </li>
                      <li class="nav-item">
                        <a href="" class="nav-link">
                          Кандидаты
                        </a>
                      </li>
                    </ul>
                  </div>
                </li>
                </ul>

              <!-- Divider -->
              <hr class="navbar-divider my-3">
              <ul class="navbar-nav">
                <li class="nav-item">
                  <a class="nav-link " href="{% url 'api:vacancy_list' %}" target="_blank">
                    Главная страница
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link " href="/admin" target="_blank">
                    Админка
                  </a>
                </li>
              </ul>


{% comment %} <script>
$(document).ready(function(){
    $('[data-toggle="startHelper"]').popover();   
});
</script> {% endcomment %}


</div>
      
              
      
              
              <!-- User (md) -->
              <div class="navbar-user d-none d-md-flex" id="sidebarUser">
        
                <!-- Icon -->
                <a href="{% static 'blog:blog_updates' %}" class="navbar-user-link" >
                  <span class="icon">
                    <i class="fe fe-bell"></i>
                  </span>
                </a>

                <!-- Dropup -->
                <div class="dropup">
          
                  <!-- Toggle -->
                  <a href="#" id="sidebarIconCopy" class="dropdown-toggle" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <div class="avatar avatar-sm avatar-online">
                      <span class="avatar-title rounded-circle">{{ request.user.first_name|make_list|first }}{{ request.user.last_name|make_list|first }}</span>
                    </div>
                  </a>

                  <!-- Menu -->
                  <div class="dropdown-menu" aria-labelledby="sidebarIconCopy">
                    <a href="profile-posts.html" class="dropdown-item disabled">Профиль <span class="ml-2 badge badge-primary">скоро</span></a>
                    {% comment %} <a href="settings.html" class="dropdown-item">Settings</a> {% endcomment %}
                    <hr class="dropdown-divider">
                    <a href="{% static 'logout' %}" class="dropdown-item">Выход</a>
                  </div>

                </div>


              </div>
              

            </div> <!-- / .navbar-collapse -->

          </div>
        </nav>
    

    <!-- MAIN CONTENT
    ================================================== -->
    <div class="main-content">

      <div class="container-fluid">
        
        {% block main %}

        {% endblock main %}

      </div>

    </div> <!-- / .main-content -->

    <!-- JAVASCRIPT
    ================================================== -->
    <script src="{% static 'libs/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'libs/@shopify/draggable/lib/es5/draggable.bundle.legacy.js' %}"></script>
    <script src="{% static 'libs/autosize/dist/autosize.min.js' %}"></script>
    <script src="{% static 'libs/chart.js/dist/Chart.min.js' %}"></script>
    <script src="{% static 'libs/dropzone/dist/min/dropzone.min.js' %}"></script>
    <script src="{% static 'libs/flatpickr/dist/flatpickr.min.js' %}"></script>
    <script src="{% static 'libs/flatpickr/dist/l10n/ru.js' %}"></script>
    <script src="{% static 'libs/highlightjs/highlight.pack.min.js' %}"></script>
    <script src="{% static 'libs/jquery-mask-plugin/dist/jquery.mask.min.js' %}"></script>
    <script src="{% static 'libs/list.js/dist/list.min.js' %}"></script>
    <script src="{% static 'libs/quill/dist/quill.min.js' %}"></script>
    <script src="{% static 'libs/select2/dist/js/select2.min.js' %}"></script>
    <script src="{% static 'libs/chart.js/Chart.extension.min.js' %}"></script>
  
    <!-- Map -->
    <script src='https://api.mapbox.com/mapbox-gl-js/v0.53.0/mapbox-gl.js'></script>

    <!-- Theme JS -->
    <script src="{% static 'js/theme.js' %}"></script>


  </body>
</html>

hr_gpb/templates/base_open.html
<!doctype html>
<html lang="ru">
  <head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">

    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'img/favicon/site.webmanifest' %}">
    <link rel="mask-icon" href="{% static 'img/favicon/safari-pinned-tab.svg' %}" color="#3690eb">
    <meta name="msapplication-TileColor" content="#2b5797">
    <meta name="theme-color" content="#ffffff">

    <!-- Libs CSS -->
    <link rel="stylesheet" href="{% static 'fonts/feather/feather.min.css' %}">
    <link rel="stylesheet" href="{% static 'libs/flatpickr/dist/flatpickr.min.css' %}">
    <link rel="stylesheet" href="{% static 'libs/quill/dist/quill.core.css' %}">
    <link rel="stylesheet" href="{% static 'libs/select2/dist/css/select2.min.css' %}">
    <link rel="stylesheet" href="{% static 'libs/highlight.js/styles/vs2015.css' %}">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fullcalendar/core@4.4.0/main.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fullcalendar/bootstrap@4.4.0/main.min.css">
    <link rel="stylesheet" href="https://unpkg.com/@fullcalendar/daygrid@4.4.0/main.min.css">

    <!-- Map -->
    <link href='https://api.mapbox.com/mapbox-gl-js/v0.53.0/mapbox-gl.css' rel='stylesheet' />

    <!-- Libs JS -->
    <script src="{% static 'libs/jquery/dist/jquery.min.js' %}"></script>

    
    <script src="https://cdn.jsdelivr.net/npm/@fullcalendar/core@4.4.0/main.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@fullcalendar/core@4.4.0/locales-all.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@fullcalendar/bootstrap@4.4.0/main.min.js"></script>
    <script src="https://unpkg.com/@fullcalendar/daygrid@4.4.0/main.min.js"></script>

    <!-- Theme CSS -->
      
    <link rel="stylesheet" href="{% static 'css/theme.min.css' %}" id="stylesheetLight">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" >

    <title>Газпромбанк HR-служба</title>

    
  </head>
  <body class="">

    <!-- NAVIGATION
    ================================================== -->
    
      
        <nav class="navbar navbar-vertical fixed-left navbar-expand-md navbar-light" id="sidebar">
          <div class="container-fluid">

            <!-- Toggler -->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#sidebarCollapse" aria-controls="sidebarCollapse" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>

            <!-- Brand -->
            <a class="navbar-brand" href="{% static 'dashboard:dashboard_web' %}">
              <img src="{% static 'img/logo.svg' %}" class="navbar-brand-img 
              mx-auto" alt="...">
            </a>

            <!-- User (xs) -->
            <div class="navbar-user d-md-none">

              <!-- Dropdown -->
              <div class="dropdown">
        
                <!-- Toggle -->
                <a href="#" id="sidebarIcon" class="dropdown-toggle" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <div class="avatar avatar-sm avatar-online">
                    <img src="{% static 'img/avatars/profiles/avatar-1.jpg' %}" class="avatar-img rounded-circle" alt="...">
                  </div>
                </a>

              </div>

            </div>

            <!-- Collapse -->
            <div class="collapse navbar-collapse" id="sidebarCollapse">

              <!-- Form -->
              {% comment %} <form class="mt-4 mb-3 d-md-none">
                <div class="input-group input-group-rounded input-group-merge">
                  <input type="search" class="form-control form-control-rounded form-control-prepended" placeholder="Поиск" aria-label="Поиск">
                  <div class="input-group-prepend">
                    <div class="input-group-text">
                      <span class="fe fe-search"></span>
                    </div>
                  </div>
                </div>
              </form> {% endcomment %}
      
              <!-- Navigation -->
              <ul class="navbar-nav">
                <li class="nav-item">
                  <a class="nav-link " href="{% static 'crm:crm_index' %}">
                    <i class="fe fe-bar-chart"></i> Дашборд
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link " href="{% url 'crm:vacancies_list' %}">
                    <i class="fe fe-gitlab"></i> Вакансии
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link " href="{% url 'crm:candidates_list' %}">
                    <i class="fe fe-users"></i> Кандидаты
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#dashboard_reports" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="dashboard_reports">
                    <i class="fe fe-command"></i> Отчеты
                  </a>
                  <div class="collapse " id="dashboard_reports">
                    <ul class="nav nav-sm flex-column">
                      <li class="nav-item">
                        <a href="" class="nav-link">
                          Итоги подбора
                        </a>
                      </li>
                      <li class="nav-item">
                        <a href="" class="nav-link">
                          Активные вакансии
                        </a>
                      </li>
                      <li class="nav-item">
                        <a href="" class="nav-link">
                          Кандидаты
                        </a>
                      </li>
                    </ul>
                  </div>
                </li>
                </ul>

              <!-- Divider -->
              <hr class="navbar-divider my-3">


{% comment %} <script>
$(document).ready(function(){
    $('[data-toggle="startHelper"]').popover();   
});
</script> {% endcomment %}


</div>
      
              
      
              
              <!-- User (md) -->
              <div class="navbar-user d-none d-md-flex" id="sidebarUser">
        
                <!-- Icon -->
                <a href="{% static 'blog:blog_updates' %}" class="navbar-user-link" >
                  <span class="icon">
                    <i class="fe fe-bell"></i>
                  </span>
                </a>

                <!-- Dropup -->
                <div class="dropup">
          
                  <!-- Toggle -->
                  <a href="#" id="sidebarIconCopy" class="dropdown-toggle" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <div class="avatar avatar-sm avatar-online">
                      <span class="avatar-title rounded-circle">{{ request.user.first_name|make_list|first }}{{ request.user.last_name|make_list|first }}</span>
                    </div>
                  </a>

                  <!-- Menu -->
                  <div class="dropdown-menu" aria-labelledby="sidebarIconCopy">
                    <a href="profile-posts.html" class="dropdown-item disabled">Профиль <span class="ml-2 badge badge-primary">скоро</span></a>
                    {% comment %} <a href="settings.html" class="dropdown-item">Settings</a> {% endcomment %}
                    <hr class="dropdown-divider">
                    <a href="{% static 'logout' %}" class="dropdown-item">Выход</a>
                  </div>

                </div>

                <!-- Icon -->
                <a href="{% static 'settings:setting_index' %}" class="navbar-user-link">
                  <span class="icon">
                    <i class="fe fe-settings"></i>
                  </span>
                </a>

              </div>
              

            </div> <!-- / .navbar-collapse -->

          </div>
        </nav>
    

    <!-- MAIN CONTENT
    ================================================== -->
    <div class="main-content">

      <div class="container-fluid">
        
        {% block main %}

        {% endblock main %}

      </div>

    </div> <!-- / .main-content -->

    <!-- JAVASCRIPT
    ================================================== -->
    <script src="{% static 'libs/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'libs/@shopify/draggable/lib/es5/draggable.bundle.legacy.js' %}"></script>
    <script src="{% static 'libs/autosize/dist/autosize.min.js' %}"></script>
    <script src="{% static 'libs/chart.js/dist/Chart.min.js' %}"></script>
    <script src="{% static 'libs/dropzone/dist/min/dropzone.min.js' %}"></script>
    <script src="{% static 'libs/flatpickr/dist/flatpickr.min.js' %}"></script>
    <script src="{% static 'libs/flatpickr/dist/l10n/ru.js' %}"></script>
    <script src="{% static 'libs/highlightjs/highlight.pack.min.js' %}"></script>
    <script src="{% static 'libs/jquery-mask-plugin/dist/jquery.mask.min.js' %}"></script>
    <script src="{% static 'libs/list.js/dist/list.min.js' %}"></script>
    <script src="{% static 'libs/quill/dist/quill.min.js' %}"></script>
    <script src="{% static 'libs/select2/dist/js/select2.min.js' %}"></script>
    <script src="{% static 'libs/chart.js/Chart.extension.min.js' %}"></script>
  
    <!-- Map -->
    <script src='https://api.mapbox.com/mapbox-gl-js/v0.53.0/mapbox-gl.js'></script>

    <!-- Theme JS -->
    <script src="{% static 'js/theme.js' %}"></script>


  </body>
</html>